server.port=8090

spring.data.mongodb.uri=mongodb+srv://collegeadmin:Anu6594@cluster0.qqoqzhe.mongodb.net/college_cloud?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=college_db

